

POST http://localhost:8080/api/requirement/create
Content-Type: application/json

{ "title": "abc", "description": "test plan", "scopes": "scope1,scope2", "tags": "tag1,tag2", "references": "http://www.google.com" }


