server:
  port: 8081
spring:
  application:
    name: xq-svc-accounts
  datasource:
    url: jdbc:h2:mem:xq-svc-accounts-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true