/*
 * TestPlan microservice
 * TestPlan microservice api documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: service.testplan@xq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xq.testplan.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.xq.testplan.api.invoker.ApiClient;
/**
 * Response
 */
@JsonPropertyOrder({
  Response.JSON_PROPERTY_STATUS_CODE,
  Response.JSON_PROPERTY_STATUS_MSG,
  Response.JSON_PROPERTY_UUID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-30T16:29:31.396499+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.12.0")
public class Response {
  public static final String JSON_PROPERTY_STATUS_CODE = "statusCode";
  @javax.annotation.Nullable
  private String statusCode;

  public static final String JSON_PROPERTY_STATUS_MSG = "statusMsg";
  @javax.annotation.Nullable
  private String statusMsg;

  public static final String JSON_PROPERTY_UUID = "uuid";
  @javax.annotation.Nullable
  private String uuid;

  public Response() { 
  }

  public Response statusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * Get statusCode
   * @return statusCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatusCode() {
    return statusCode;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
  }


  public Response statusMsg(@javax.annotation.Nullable String statusMsg) {
    this.statusMsg = statusMsg;
    return this;
  }

  /**
   * Get statusMsg
   * @return statusMsg
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_MSG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatusMsg() {
    return statusMsg;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_MSG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusMsg(@javax.annotation.Nullable String statusMsg) {
    this.statusMsg = statusMsg;
  }


  public Response uuid(@javax.annotation.Nullable String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Get uuid
   * @return uuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(@javax.annotation.Nullable String uuid) {
    this.uuid = uuid;
  }


  /**
   * Return true if this Response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.statusCode, response.statusCode) &&
        Objects.equals(this.statusMsg, response.statusMsg) &&
        Objects.equals(this.uuid, response.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, statusMsg, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMsg: ").append(toIndentedString(statusMsg)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `statusCode` to the URL query string
    if (getStatusCode() != null) {
      joiner.add(String.format("%sstatusCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusCode()))));
    }

    // add `statusMsg` to the URL query string
    if (getStatusMsg() != null) {
      joiner.add(String.format("%sstatusMsg%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusMsg()))));
    }

    // add `uuid` to the URL query string
    if (getUuid() != null) {
      joiner.add(String.format("%suuid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUuid()))));
    }

    return joiner.toString();
  }
}

