services:
  xq-ms-test-plan:
    image: xq-ms-test-plan:latest
    container_name: xq-ms-test-plan
    restart: on-failure
    ports:
      - "3000:8080"
    environment:
      - JAVA_OPTS=-Xms300m -Xmx512m
    volumes:
      - ./logs:/app/logs
    networks:
      - xq-network

networks:
  xq-network:
    driver: "bridge"