version: '3.8'

services:
  fungus-accounts:
    image: xq/fungus-loans:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "component"
