openapi: 3.0.1
info:
  contact:
    email: service.testplan@xq.com
    name: David Chau
    url: https://xq.com
  description: TestPlan microservice api documentation
  license:
    name: Apache 2.0
  title: TestPlan microservice
  version: v1
externalDocs:
  description: external documentation
  url: http://localhost:8080/swagger-ui/index.html
servers:
- description: Generated server url
  url: http://localhost:8080
tags:
- description: REST APIS for TestPlan service
  name: REST APIS  TestPlan
paths:
  /api/requirement/update:
    put:
      description: API endpoint to update a test requirement by input request
      operationId: updateAccount
      parameters:
      - explode: true
        in: query
        name: uuid
        required: true
        schema:
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Requirement"
        required: true
      responses:
        "417":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: Expectation failed
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Http status internal server error - can not update a test requirement
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: Http status success
      summary: Update a test requirement
      tags:
      - REST APIS  TestPlan
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/requirement/create:
    post:
      description: API endpoint to create a test requirement information by input
        request
      operationId: createRequirement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Requirement"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: Http status created
      summary: Create a test requirement
      tags:
      - REST APIS  TestPlan
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/requirement/{uuid}:
    get:
      description: API endpoint to get a test requirement information by uuid
      operationId: fetchRequirement
      parameters:
      - explode: false
        in: path
        name: uuid
        required: true
        schema:
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Requirement"
          description: Http status success
      summary: Get a test requirement
      tags:
      - REST APIS  TestPlan
      x-accepts:
      - application/json
  /api/requirement/all:
    get:
      description: API endpoint to get all test requirements
      operationId: getAllRequirements
      responses:
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: An error occurred. Please try again or contact product support
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListRequirementsDto"
          description: Request processed successfully
      summary: Get all test requirements
      tags:
      - REST APIS  TestPlan
      x-accepts:
      - application/json
  /api/requirement/delete:
    delete:
      description: API endpoint to delete a test requirement by uuid
      operationId: deleteAccount
      parameters:
      - explode: true
        in: query
        name: uuid
        required: true
        schema:
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          type: string
        style: form
      responses:
        "417":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: Expectation failed
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: Http status success
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Http status internal server error - can not delete a test requirement
      summary: Delete a test requirement
      tags:
      - REST APIS  TestPlan
      x-accepts:
      - application/json
  /api/requirement/delete/all:
    delete:
      description: API endpoint to delete all test requirements
      operationId: deleteAllRequirements
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: Http status success
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: An error occurred. Please try again or contact product support
      summary: Delete all test requirements
      tags:
      - REST APIS  TestPlan
      x-accepts:
      - application/json
components:
  schemas:
    Requirement:
      description: Requirement request payload object
      example:
        references: "Reference1, Reference2"
        description: Requirement Description
        scopes: "Scope1, Scope2"
        title: Requirement Title
        tags: "Tag1, Tag2"
      properties:
        title:
          description: Requirement title
          example: Requirement Title
          maxLength: 100
          minLength: 0
          type: string
        description:
          description: Requirement description
          example: Requirement Description
          maxLength: 500
          minLength: 0
          type: string
        scopes:
          description: Requirement scopes
          example: "Scope1, Scope2"
          maxLength: 500
          minLength: 0
          type: string
        tags:
          description: Requirement tags
          example: "Tag1, Tag2"
          maxLength: 200
          minLength: 0
          type: string
        references:
          description: Requirement references
          example: "Reference1, Reference2"
          maxLength: 500
          minLength: 0
          type: string
      required:
      - description
      - references
      - scopes
      - tags
      - title
      type: object
    ErrorResponse:
      example:
        errorTime: 2000-01-23T04:56:07.000+00:00
        apiPath: uri=/api/requirements/update
        errorMessage: Requirement not found with the given input data requirement
          uuid:'1234-5661-1235-1232-5112'
        errorCode: NOT_FOUND
      properties:
        apiPath:
          example: uri=/api/requirements/update
          type: string
        errorCode:
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 EARLY_HINTS
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
          example: NOT_FOUND
          type: string
        errorMessage:
          description: Error message returned from implementation logic
          example: Requirement not found with the given input data requirement uuid:'1234-5661-1235-1232-5112'
          type: string
        errorTime:
          description: Date time when error occur
          format: date-time
          type: string
      type: object
    Response:
      example:
        statusMsg: statusMsg
        uuid: uuid
        statusCode: statusCode
      properties:
        statusCode:
          type: string
        statusMsg:
          type: string
        uuid:
          type: string
      type: object
    ListRequirementsDto:
      description: Requirements response payload object
      example:
        total: 5
        requirements:
        - references: "Reference1, Reference2"
          description: Requirement Description
          scopes: "Scope1, Scope2"
          title: Requirement Title
          tags: "Tag1, Tag2"
        - references: "Reference1, Reference2"
          description: Requirement Description
          scopes: "Scope1, Scope2"
          title: Requirement Title
          tags: "Tag1, Tag2"
      properties:
        total:
          description: Total number of requirements
          example: 5
          format: int32
          type: integer
        requirements:
          description: List of requirement objects
          items:
            $ref: "#/components/schemas/Requirement"
          type: array
      type: object

